language: python

python:
    - "3.4"
    - "3.5"
    - "nightly"

cache: pip

install:
    - "pip install -r requirements.txt"

before-script:
    - "python manage.py migrate"

script: 
    - "python manage.py test"
