language: python

python:
    - "3.4"
    - "3.5"
    - "nightly"

node_js:
    - "6.1"

services:
    - postgresql

cache: pip

addons:
    postgresql: "9.4"

env:
    - DJANGO_SETTINGS_MODULE=oils.settings.test

install:
    - travis_retry make setup_test -C demo/hackerlibrary

before_install:
    - pip install codecov

script: 
    - make test -C demo/hackerlibrary

after_success:
    - codecov
