language: python

python:
    - "3.4"
    - "3.5"
    - "nightly"

cache: pip

install:
    - "pip install -r requirements.txt"

before-script:
    - "python manage.py migrate"

before_install:
    - pip install codecov

after_success:
    - codecov

script: 
    - "coverage run --source='.' manage.py test"
